const cakeData = [
  {
    img: "1920s_cake.JPG",
    name: "Art Deco Murder Mystery Cake",
    caption:
      "Champagne cake, strawberry champagne jam, lemon buttercream decorations, and strawberry champagne coulis blood",
    medium: "cake",
    tag: "cake",
    alt: "photo of a sqaure cake with black and white diamond checkered pattern",
    importName: "cake1",
    id: 1,
    width: 720,
    height: 900,
  },
  {
    img: "alien_cake.JPG",
    name: "Alien Lion Smash Cake and Matching Party Cake",
    caption:
      "Funfetti cake with freeze dried blueberries, blueberry/strawberry jam, pandon cream cheese frosting interior, pandon buttercream decorations",
    medium: "cake",
    tag: "cake",
    alt: "photo of a large cake with an alien on it and small cake that looks like a lion with three eyes",
    importName: "cake2",
    id: 2,
    width: 720,
    height: 900,
  },
  {
    img: "frog_cake.JPG",
    name: "Marzipan Frog Party Cake",
    caption:
      "Chocolate cake, vanilla pastry cream, espresso buttercream, marzipan/sprinkle decorations",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round cake with a marzipan sculpted frog making a cake and preparing for a party",
    importName: "cake3",
    id: 3,
    width: 720,
    height: 900,
  },
  {
    img: "girl_power_cake.JPG",
    name: "Girl Power Cake",
    caption:
      "Lemon cake, grapefruit jam, taro buttercream interior, vanilla buttercream decorations",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round cake with flowers that says girl power",
    importName: "cake4",
    id: 4,
    width: 720,
    height: 900,
  },
  {
    img: "daisy_cake.JPG",
    name: "Funky Flower Cake",
    caption:
      "Elderflower lemon cake, lemon curd, lemony cream cheese frosting, lemon buttercream decorations",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round cake with piped daises and cherries on top",
    importName: "cake5",
    id: 5,
    width: 720,
    height: 900,
  },
  {
    img: "living_room_cake.JPG",
    name: "Marzipan Living Room Cake",
    caption: "Chocolate cake, crunchy espresso frosting, marzipan decorations",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round cake with living room scene sculpted from marzipan",
    importName: "cake6",
    id: 6,
    width: 720,
    height: 897,
  },
  {
    img: "shell_cake.jpg",
    name: "Seashell in Beach House Furniture Color Scheme",
    caption: "Vanilla cake, guava jam, cream cheese frosting",
    medium: "cake",
    tag: "cake",
    alt: "photo of a cake shaped like a seashell",
    importName: "cake7",
    id: 7,
    width: 1008,
    height: 1344,
  },
  {
    img: "shag_check_cake.jpg",
    name: "Funky Diamond Print Shag Cake",
    caption:
      "Chocolate cake, raspberry passionfruit jam, raspberry buttercream interior, vanilla and chocolate buttercream decorations",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round shag carpet textured cake with a black and white checkerboard print",
    importName: "cake8",
    id: 8,
    width: 1008,
    height: 1344,
  },
  {
    img: "daisy_airbrush_cake.jpg",
    name: "Airbrush Daisy Cake",
    caption:
      "Taro cake, lemon curd, strawberry taro buttercream interior, lime buttercream decorations",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round cake with airbrushed daisies",
    importName: "cake9",
    id: 9,
    width: 1008,
    height: 1344,
  },
  {
    img: "squiggle_cake.jpg",
    name: "Squiggle Cake",
    caption:
      "Ube cake, strawberry jam, pandon buttercream interior, vanilla buttercream decorations",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round cake with squiggles and cherries on top",
    importName: "cake10",
    id: 10,
    width: 1008,
    height: 1344,
  },
  {
    img: "squiggle2_cake.jpg",
    name: "Squiggle Cake",
    caption: "Carrot cake, cream cheese frosting",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round cake with squiggles and cherries on top",
    importName: "cake11",
    id: 11,
    width: 1008,
    height: 1344,
  },
  {
    img: "butterfuly_cake.jpg",
    name: "Butterfly Airbrush Cake",
    caption:
      "Funfetti cake, chocolate and strawberry cream cheese frosting interior, vanilla buttercream decorations",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round cake with airbrushed butterflies",
    importName: "cake12",
    id: 12,
    width: 1008,
    height: 1344,
  },
  {
    img: "witch_cake.jpg",
    name: "Witches' Brew Halloween Cake",
    caption:
      "Spiced chocolate cake, pepita crunch, butterscotch buttercream interior, vanilla buttercream decorations, white chocolate drip",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round cake with a purple witch hand, snake, and eyeball",
    importName: "cake13",
    id: 13,
    width: 1008,
    height: 1344,
  },
  {
    img: "lisafrank_cake.jpg",
    name: "Lisa Frank Rainbow Tiger Print Cake",
    caption: "Carrot cake with cream cheese frosting",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round rainbow colored cake with tiger stripes",
    importName: "cake14",
    id: 14,
    width: 1008,
    height: 1344,
  },
  {
    img: "fall_shag_cake.jpg",
    name: "70s Patterned Shag Cake",
    caption:
      "Chocolate cake, passionfruit curd, chocolate buttercream interior, chocolate and vanilla buttercream decorations",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round cake with shag carpet texture in a 1970s print",
    importName: "cake15",
    id: 15,
    width: 1008,
    height: 1344,
  },
  {
    img: "heart_cake.jpg",
    name: "Frilly Heart Cake",
    caption: "Vanilla cake with vanilla buttercream",
    medium: "cake",
    tag: "cake",
    alt: "photo of a heart shaped cake with frilly decorations and cherries on top",
    importName: "cake16",
    id: 16,
    width: 1008,
    height: 1344,
  },
  {
    img: "bo_peep_cake.jpg",
    name: "Frilly Bo Peep Cake",
    caption:
      "Chocolate cake, passionfruit curd, chocolate buttercream interior, lime buttercream decorations",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round cake in pastel colors with frills and cherries on top",
    importName: "cake17",
    id: 17,
    width: 1008,
    height: 1344,
  },
  {
    img: "checkered_cake.jpg",
    name: "Soft Punk Pastel Checkered Cake",
    caption:
      "Funfetti cake, espresso cream cheese frosting interior, vanilla buttercream decorations",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round pastel checkerboard cake",
    importName: "cake18",
    id: 18,
    width: 1008,
    height: 1344,
  },
  {
    img: "valentines_mini_cakes.jpg",
    name: "Valentine's Day Mini Cakes",
    caption:
      "Mini cakes for Bird in Hand Cafe & Bookstore's Valentine's Day bundles -Chocolate cake with raspberry jam and vanilla buttercream and vanilla cake with lemon curd and vanilla buttercream",
    medium: "cake",
    tag: "cake",
    alt: "photo of a round mini cakes with abstract pallet brush marks like that of a painting",
    importName: "cake19",
    id: 19,
    width: 1008,
    height: 1344,
  },
];

export default cakeData;
