const graphicDesignData = [
  {
    img: "BB_Stretch.png",
    name: "Stretch Poster for BB Boxing Club",
    caption: "Digital Illustration, Layout Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of an illustrated poster of workout stretches being demonstrated by fat femme and queer people",
    id: 1,
    orientation: "portrait",
  },
  {
    img: "Yellow_Burg.png",
    name: "Rats",
    caption: "Digital Illustration",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of an illustration of two dogs and a cat playing poker with the word Rats",
    id: 2,
    orientation: "landscape",
  },
  {
    img: "Jetski_Puzzle.png",
    name: "Jet Ski",
    caption: "Digital Illustration",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of an illustration of a sunburned blonde woman on a 90s jet ski with dolphins swimming around her",
    id: 3,
    orientation: "landscape",
  },
  {
    img: "FatSk8_All_Pink.png",
    name: "Fat Sk8r",
    caption: "Digital Illustrations",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of several illustrations including a butt sitting on a skateboard, a beer belly tshirt saying fat sk8r, a cherub cuddling a Truly, a cherub cuddling a skateboard, a mouth and tongue, a beer belly with a tattoo reading fat sk8r, a small chubby beer can that says fat sk8r on the label, a mouth and wavy font that says fat sk8r",
    id: 4,
    orientation: "portrait",
  },
  {
    img: "periwinkle_berry.png",
    name: "Drunk & Disorderly",
    caption: "Digital Illustration",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of an illustration of a woman passed out on a floral couch surrounded by a mess of leftover food, clothing, and booze with the title Drunk & Disorderly and the caption A Brave Look Back on Our Twenties",
    id: 5,
    orientation: "portrait",
  },
  {
    img: "PorchProm2022_CampCamp_WithBackground.png",
    name: "Artwork Design for Abell Neighborhood's 3rd Annual Porch Prom Event",
    caption: "Digital Illustration",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of an illustration of raccoons dressed in camping equipment dancing around a tent at a campsite",
    id: 6,
    orientation: "portrait",
  },
  {
    img: "BHB_Premie_Collage_Transparent_Landscape.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Assets",
    caption: "Digital Illustration",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a series of illustrations such as a woman with a doctor, a man and pregnant woman making dinner, a father helping his child take his first steps, a baby sleeping in a crib, a diagram of a pregnant woman's body from the profile view",
    id: 7,
    orientation: "x-w landscape",
  },
  {
    img: "PremieAwareness_5Points_Flyer.png",
    name: "B'more for Healthy Babies Prematurity Awareness One Pager",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a one pager about prematurity awareness",
    id: 8,
    orientation: "portrait",
  },
  {
    img: "PremieAwareness_IG_1.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic with a pregnant woman talking to her doctor",
    id: 9,
    orientation: "square",
  },
  {
    img: "PremieAwareness_IG_2.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic with a diagram of a pregnant woman's body from the profile view",
    id: 10,
    orientation: "square",
  },
  {
    img: "PremieAwareness_IG_3.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic with a diagram of a man and pregnant woman making dinner",
    id: 11,
    orientation: "square",
  },
  {
    img: "PremieAwareness_IG_4.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic with hands holding info materials about birth control",
    id: 12,
    orientation: "square",
  },
  {
    img: "PremieAwareness_IG_5.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of a pregnant woman walking and talking with a female family member",
    id: 13,
    orientation: "square",
  },
  {
    img: "PremieAwareness_IG_6.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of a woman's legs in the tub taking a bubble bath",
    id: 14,
    orientation: "square",
  },
  {
    img: "SafeSleepPremies_IG_1.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Safe Sleep Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of a baby sleeping on their back in a crib",
    id: 15,
    orientation: "square",
  },
  {
    img: "SafeSleepPremies_IG_2.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Safe Sleep Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of a mother putting her baby in a crib next to her bed",
    id: 16,
    orientation: "square",
  },
  {
    img: "SafeSleepPremies_IG_3.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Safe Sleep Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of a baby sleeping on their back in a crib",
    id: 17,
    orientation: "square",
  },
  {
    img: "SafeSleepPremies_IG_4.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Safe Sleep Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of a baby sleeping on their back in a crib with a basket next to the crib holding blankets and a teddy bear",
    id: 18,
    orientation: "square",
  },
  {
    img: "SafeSleepPremies_IG_5.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Safe Sleep Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of vapes and marijuana exed out so as to say do not smoke",
    id: 19,
    orientation: "square",
  },
  {
    img: "DidYouKnow_IG_1.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of a map of the United States with a scale",
    id: 20,
    orientation: "square",
  },
  {
    img: "DidYouKnow_IG_2.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of a father helping his child take his first steps",
    id: 21,
    orientation: "square",
  },
  {
    img: "DidYouKnow_IG_3.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of women of three different skin tones holding their pregnant stomachs",
    id: 22,
    orientation: "square",
  },
  {
    img: "DidYouKnow_IG_4.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of a pregnant woman holding her back while having contractions",
    id: 23,
    orientation: "square",
  },
  {
    img: "DidYouKnow_IG_5.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of an envelope with a medical bill",
    id: 24,
    orientation: "square",
  },
  {
    img: "BHBHoliday_Graphic1.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of a mother and father watching their baby sleep in a crib",
    id: 25,
    orientation: "square",
  },
  {
    img: "BHBHoliday_Graphic2.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of a mother and father watching their baby crawl in their cozy living room",
    id: 26,
    orientation: "square",
  },
  {
    img: "BHBHoliday_Graphic3.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of husbands with their two children. One husband is making cookies with their daughter while the other husband holds their newborn baby",
    id: 27,
    orientation: "square",
  },
  {
    img: "BHBHoliday_Graphic4.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of a family of four on their couch watching tv",
    id: 28,
    orientation: "square",
  },
  {
    img: "BHBHoliday_Graphic5.png",
    name: "B'more for Healthy Babies Prematurity Awareness Campaign Social Media Graphic",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of two phone screens showing a Facetime between a two female friends",
    id: 29,
    orientation: "square",
  },
  {
    img: "SizeChart_Yellow_Brown.png",
    name: "Nail Size Chart",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a social media graphic of fingers with long nails and measurements for the width of each nail",
    id: 30,
    orientation: "square",
  },
  {
    img: "mapback.png",
    name: "Folding Map (1/2)",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a flat map",
    id: 31,
    orientation: "x-w landscape",
  },
  {
    img: "StMarysMap.png",
    name: "Folding Map (2/2)",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a flat map",
    id: 32,
    orientation: "x-w landscape",
  },
  {
    img: "Housewarming opt2_color 1.png",
    name: "Housewarming Flyer",
    caption: "Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a flyer with squiggly lines",
    id: 33,
    orientation: "portrait",
  },
  {
    img: "HMC_Collage.png",
    name: "Harvest Moon Doula Logo Concepts",
    caption: "Digital Illustration",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of moon logos",
    id: 34,
    orientation: "landscape",
  },
  {
    img: "COVIDFAQ.png",
    name: "Baltimore City Public Schools and Baltimore City Health Department Covid-19 Vaccination for Children FAQ One Pager",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a one pager with images of a father and son and students in masks with bandages on their arm from their covid-19 vaccine",
    id: 35,
    orientation: "x-w landscape",
  },
  {
    img: "BirthAnnouncement_Option3_Edited.jpg",
    name: "B'more for Healthy Babies Birth Announcement Yard Sign with Safe Sleep Tips",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of a baby sleeping on their back in a crib",
    id: 36,
    orientation: "landscape",
  },
  {
    img: "BB_BizCard_logo_3.png",
    name: "Bunty Bakes (My Cake Biz) Logo and Business Card",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of Bunty Bakes Logo and square business card decorated with vintage diamond print and cherries",
    id: 37,
    orientation: "x-w landscape",
  },
  {
    img: "BBCakeMenu2.png",
    name: "Bunty Bakes (My Cake Biz) Menu Graphics for Instagram Stories",
    caption: "Digital Illustration, Graphic Design",
    medium: "Digital Illustration",
    tag: "digital",
    alt: "photo of Bunty Bakes menu graphics for Instagram stories decorated with vintage diamond print and cherries",
    id: 38,
    orientation: "x-w landscape",
  },
];

export default graphicDesignData;
