const printIllustrationData = [
  {
    img: "Staircase_edited.jpg",
    name: "Green House Staircase",
    caption: "Gel pen on black paper",
    medium: "Print Illustration",
    tag: "print",
    alt: "photo of a gel pen line drawing on black paper of a wallpapered 1970s foyer with spiral staircase",
    id: 1,
  },
  {
    img: "HotTub_edited.jpg",
    name: "Spa Day",
    caption: "Gel pen on black paper",
    medium: "Print Illustration",
    tag: "print",
    alt: "photo of a gel pen line drawing on black paper of a hot tub",
    id: 2,
  },
  {
    img: "SquareConversationPit_edited.jpg",
    name: "Conversation Pit Jelly Dome",
    caption: "Gel pen on black paper",
    medium: "Print Illustration",
    tag: "print",
    alt: "photo of a gel pen line drawing on black paper of a 1960s living room with a square conversation pit sofa",
    id: 3,
  },
  {
    img: "Tropical_pit_edited.jpg",
    name: "Conversation Pit Pineapple Upside Down Cake",
    caption: "Gel pen on black paper",
    medium: "Print Illustration",
    tag: "print",
    alt: "photo of a gel pen line drawing on black paper of a 1960s tropical living room with a round conversation pit sofa",
    id: 4,
  },
  {
    img: "Circles_edited.jpg",
    name: "Conversation Pit Baked Alaska",
    caption: "Gel pen on black paper",
    medium: "Print Illustration",
    tag: "print",
    alt: "photo of a gel pen line drawing on black paper of a 1960s living room with a round conversation pit sofa",
    id: 5,
  },
  {
    img: "Futurism_Chrome_edited.jpg",
    name: "Chrome Room",
    caption: "Gel pen on black paper",
    medium: "Print Illustration",
    tag: "print",
    alt: "photo of a gel pen line drawing on black paper of a 1960s dining room and living room with chrome accents",
    id: 6,
  },
  {
    img: "DiningRoom_edited.jpg",
    name: "Circular Dining",
    caption: "Gel pen on black paper",
    medium: "Print Illustration",
    tag: "print",
    alt: "photo of a gel pen line drawing on black paper of a 1960s dining room with circle pattern on walls and rug",
    id: 7,
  },
  {
    img: "Rentals_edited.jpg",
    name: "Roller Rink Food Court",
    caption: "Gel pen on black paper",
    medium: "Print Illustration",
    tag: "print",
    alt: "photo of a gel pen line drawing on black paper of a patterned carpeted roller rink food court and skate rentals counter",
    id: 8,
  },
  {
    img: "Skateland_edited.jpg",
    name: "Skateland",
    caption: "Gel pen on black paper",
    medium: "Print Illustration",
    tag: "print",
    alt: "photo of a gel pen line drawing on black paper of an empty roller rink with disco ball and lights on the ceiling",
    id: 9,
  },
  {
    img: "Rentals_Cake_edited.jpg",
    name: "Roller Rink Rentals",
    caption: "Gel pen on black paper",
    medium: "Print Illustration",
    tag: "print",
    alt: "photo of a gel pen line drawing on black paper of a patterned carpeted roller rink skate rentals counter with a dropped birthday cake on the ground",
    id: 10,
  },
  {
    img: "RollerRink_Lights_edited.jpg",
    name: "Roller Rink Lights",
    caption: "Gel pen on black paper",
    medium: "Print Illustration",
    tag: "print",
    alt: "photo of a gel pen line drawing on black paper of an empty roller rink with lights covering the entire ceiling",
    id: 11,
  },
];

export default printIllustrationData;
