import Navigation from "./components/navigation";
import "./globals.css";
import type { Metadata } from "next";
import { Cutive_Mono } from "next/font/google";

const cutiveMono = Cutive_Mono({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alex Bunty Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cutiveMono.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
